//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bio.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bio.Core.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find complement for one or more symbols..
        /// </summary>
        internal static string ComplementNotFound {
            get {
                return ResourceManager.GetString("ComplementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not recognize the specified symbol..
        /// </summary>
        internal static string CouldNotRecognizeSymbol {
            get {
                return ResourceManager.GetString("CouldNotRecognizeSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count cannot be less than zero.
        /// </summary>
        internal static string CountCannotBeLessThanZero {
            get {
                return ResourceManager.GetString("CountCannotBeLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Array Not Large Enough.
        /// </summary>
        internal static string DestArrayNotLargeEnough {
            get {
                return ResourceManager.GetString("DestArrayNotLargeEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dna.
        /// </summary>
        internal static string DnaAlphabetName {
            get {
                return ResourceManager.GetString("DnaAlphabetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter is invalid..
        /// </summary>
        internal static string InvalidParameter {
            get {
                return ResourceManager.GetString("InvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified argument was out of the range it must be non negative and less than the count of this sequence..
        /// </summary>
        internal static string ParameterMustLessThanCount {
            get {
                return ResourceManager.GetString("ParameterMustLessThanCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified argument was out of the range it must be non negative..
        /// </summary>
        internal static string ParameterMustNonNegative {
            get {
                return ResourceManager.GetString("ParameterMustNonNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to array.
        /// </summary>
        internal static string ParameterNameArray {
            get {
                return ResourceManager.GetString("ParameterNameArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start.
        /// </summary>
        internal static string ParameterNameStart {
            get {
                return ResourceManager.GetString("ParameterNameStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protein.
        /// </summary>
        internal static string ProteinAlphabetName {
            get {
                return ResourceManager.GetString("ProteinAlphabetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rna.
        /// </summary>
        internal static string RnaAlphabetName {
            get {
                return ResourceManager.GetString("RnaAlphabetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start cannot be less than zero.
        /// </summary>
        internal static string StartCannotBeLessThanZero {
            get {
                return ResourceManager.GetString("StartCannotBeLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartData can not be null or empty..
        /// </summary>
        internal static string StartDataCannotBeNull {
            get {
                return ResourceManager.GetString("StartDataCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol already exists in alphabet..
        /// </summary>
        internal static string SymbolExistsInAlphabet {
            get {
                return ResourceManager.GetString("SymbolExistsInAlphabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}... +[{1}].
        /// </summary>
        internal static string ToStringFormat {
            get {
                return ResourceManager.GetString("ToStringFormat", resourceCulture);
            }
        }
    }
}
